{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.databinding",
    "module": "databinding-ktx",
    "version": "7.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-service",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "databinding-ktx-7.2.0.aar",
          "url": "databinding-ktx-7.2.0.aar",
          "size": 10724,
          "sha512": "ef5b3a3aa1b3494bb5c7391a1d611501fc66fd127172797134e3bc2c12a3ae69c7a628a5497f6713d68c620a72e3eb303ee3c8f47a5aaae8af84c71306ddfe22",
          "sha256": "382bb0ec9b3b6d330c71dc261f1e3e5562c88179241104a4ca65bb469f5e53e0",
          "sha1": "cd1292298ac9ca08bf24c4386c4dfea0bf4b1dc1",
          "md5": "c1e86d7e05a5c0b85f89825070162eca"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-service",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "databinding-ktx-7.2.0.aar",
          "url": "databinding-ktx-7.2.0.aar",
          "size": 10724,
          "sha512": "ef5b3a3aa1b3494bb5c7391a1d611501fc66fd127172797134e3bc2c12a3ae69c7a628a5497f6713d68c620a72e3eb303ee3c8f47a5aaae8af84c71306ddfe22",
          "sha256": "382bb0ec9b3b6d330c71dc261f1e3e5562c88179241104a4ca65bb469f5e53e0",
          "sha1": "cd1292298ac9ca08bf24c4386c4dfea0bf4b1dc1",
          "md5": "c1e86d7e05a5c0b85f89825070162eca"
        }
      ]
    }
  ]
}
