{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.databinding",
    "module": "databinding-adapters",
    "version": "7.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "databinding-adapters-7.2.0.aar",
          "url": "databinding-adapters-7.2.0.aar",
          "size": 81798,
          "sha512": "ca562788d51234212508d0bdba23790f1bff61ed1c92af2dcb3491a0075385a1b06084f2a8eec620ffe5ab0125d920f41a59bed58c6e9b97ab7a4d9852e4a7ef",
          "sha256": "4d1259dcbf47fe791801aa130d3ec45d011662a134dbed10164ba1a50ffee65a",
          "sha1": "31e0627bf5413d7b03b02570fd443c32381cfa4a",
          "md5": "a456bf4985b4a948e4ac29d5525a9b36"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "databinding-adapters-7.2.0.aar",
          "url": "databinding-adapters-7.2.0.aar",
          "size": 81798,
          "sha512": "ca562788d51234212508d0bdba23790f1bff61ed1c92af2dcb3491a0075385a1b06084f2a8eec620ffe5ab0125d920f41a59bed58c6e9b97ab7a4d9852e4a7ef",
          "sha256": "4d1259dcbf47fe791801aa130d3ec45d011662a134dbed10164ba1a50ffee65a",
          "sha1": "31e0627bf5413d7b03b02570fd443c32381cfa4a",
          "md5": "a456bf4985b4a948e4ac29d5525a9b36"
        }
      ]
    }
  ]
}
